### ISSUE TITLE
Crash in Object-C

### ISSUE THREAD

**Issue by jihongboo** [marty-suzuki/ReverseExtension#14]
UMLOG: error: session_id=0A305CA2267A57BCE3328B677E10407C, context=An instance 0x7fab039b2400 of class UITableView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x61000023b420> (
<NSKeyValueObservance 0x61000045e690: Observer: 0x6100001de4b0, Key path: contentInset, Options: <New: YES, Old: YES, Prior: NO> Context: 0x0, Property: 0x608000440d80>

Can you help me with this problem?

**Comment by marty-suzuki** [comment]
What version of ReverseExtension do you install on your app?

**Comment by jihongboo** [comment]
The version is 0.4.0.
Beside I fond a Temporary solution.
I put
` [tableview removeObserver: tableview.re forKeyPath:@"contentInset"];`
into
`viewWillDisappear:(BOOL)animated`
and it will not crash anymore.

**Comment by jihongboo** [comment]
I have updated to 0.4.5 and found out that the bug has been fixed, thank you.😁

**Comment by marty-suzuki** [comment]
Thank you for updating latest version!
