### ISSUE TITLE
origin table is reversed

### ISSUE THREAD

**Issue by yfde11** [marty-suzuki/ReverseExtension#15]
Excuse me, I have a tableview to show all things, after I install your framework, and use in my target page, until here is fine, but when I back the last page the tableview is reverse.

![ask1](https://cloud.githubusercontent.com/assets/5066834/24945864/87864714-1f93-11e7-9049-a21d5f95848f.gif)

**Comment by marty-suzuki** [comment]
Do you access `tableView.re` in 車行列表ViewController?

**Comment by marty-suzuki** [comment]
I've fixed this issue. Please try v0.4.6!

**Comment by yfde11** [comment]
it works!!! Thank you so much.

**Comment by marty-suzuki** [comment]
Great!! Thank you for your reporting.
