### ISSUE TITLE
Crash When Scrolling to the Top

### ISSUE THREAD

**Issue by mredig** [marty-suzuki/ReverseExtension#38]
In Xcode 10/Swift 4.2/iOS 12 Simulator, both my app and the included sample app crash if there are tableviewcells on the table and you try to scroll beyond the top of the view.

The issue doesn't seem to appear in Xcode 9/Swift 4.1/iOS 11.

**Comment by alexeybolv** [comment]
Hi, did you find any solution?

**Comment by mredig** [comment]
I have not investigated any further. It'd be worth another test as new versions of the beta have been released since this issue occurred.

**Comment by mredig** [comment]
It appears that the issue was with the beta and not in this library. I've tested with the latest versions of everything, swift, Xcode, iOS 12, and this library, and the bug has not resurfaced in my tests.
