### ISSUE TITLE
Misspell of indexPath and  in rectForRow unused variable

### ISSUE THREAD

**Issue by oyalhi** [marty-suzuki/ReverseExtension#7]
In ReverseExtension.swift, in function rectForRow, indexPath is misspelled; therefore, using the incorrect variable may cause weird behavior:

```
        public func rectForRow(at indexPath: IndexPath) -> CGRect {
            let indexPaht = reversedIndexPath(with: indexPath)
            return nonNilBase.rectForRow(at: indexPath)
        }
```

**indexPaht** should be **indexPath**

**Comment by marty-suzuki** [comment]
Thank you for your reporting!
I've fixed it!
